name: deploy
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name: Install caprover
        run: npm install -g caprover

      - name: Caprover Deploy
        run: caprover deploy -h '${{ secrets.CAPROVER_SERVER }}' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'master' -a '${{ secrets.CAPROVER_APP_NAME }}'

    #   - uses: AlexxNB/caprover-action@v1
    #     with:
    #       server: '${{ secrets.CAPROVER_SERVER }}'
    #       password: '${{ secrets.CAPROVER_PASSWORD }}'
    #       appname: '${{ secrets.CAPROVER_APP_NAME }}'
